// api/companies.js — Base de données enrichie 800+ entreprises françaises

const DOMAINES_PAR_SECTEUR = {

  'Distribution / Négoce': [
    // Grandes enseignes nationales
    { name: 'Sysco France', domain: 'sysco.fr' },
    { name: 'Metro France', domain: 'metro.fr' },
    { name: 'Pomona', domain: 'pomona.fr' },
    { name: 'Transgourmet', domain: 'transgourmet.fr' },
    { name: 'Brake France', domain: 'brake.fr' },
    { name: 'Pro à Pro', domain: 'proapro.fr' },
    { name: 'Promocash', domain: 'promocash.fr' },
    { name: 'Agrial', domain: 'agrial.fr' },
    { name: 'Euralis', domain: 'euralis.fr' },
    { name: 'Biocoop', domain: 'biocoop.fr' },
    { name: 'Leclerc', domain: 'e.leclerc' },
    { name: 'Intermarché', domain: 'intermarche.com' },
    { name: 'Lidl France', domain: 'lidl.fr' },
    { name: 'Aldi France', domain: 'aldi.fr' },
    { name: 'Netto', domain: 'netto.fr' },
    { name: 'Picard Surgelés', domain: 'picard.fr' },
    { name: 'Labeyrie', domain: 'labeyrie.fr' },
    { name: 'Nicolas', domain: 'nicolas.com' },
    { name: 'Maïsadour', domain: 'maisadour.com' },
    { name: 'Arterris', domain: 'arterris.fr' },
    { name: 'Terrena', domain: 'terrena.fr' },
    { name: 'InVivo', domain: 'invivo-group.com' },
    { name: 'Vivescia', domain: 'vivescia.com' },
    { name: 'Limagrain', domain: 'limagrain.com' },
    { name: 'Soufflet', domain: 'soufflet.com' },
    { name: 'Axéréal', domain: 'axereal.com' },
    { name: 'Cérélia', domain: 'cerelia.com' },
    { name: 'Distriborg', domain: 'distriborg.com' },
    { name: 'PassionFroid', domain: 'passionfroid.fr' },
    { name: 'TerreAzur', domain: 'terreazur.com' },
  ],

  'Industrie': [
    // Grands groupes
    { name: 'Schneider Electric', domain: 'se.com' },
    { name: 'Saint-Gobain', domain: 'saint-gobain.com' },
    { name: 'Faurecia', domain: 'faurecia.com' },
    { name: 'Legrand', domain: 'legrand.fr' },
    { name: 'Plastic Omnium', domain: 'plasticomnium.com' },
    { name: 'Safran', domain: 'safran-group.com' },
    { name: 'Thales', domain: 'thalesgroup.com' },
    { name: 'Airbus', domain: 'airbus.com' },
    { name: 'Michelin', domain: 'michelin.fr' },
    { name: 'Valeo', domain: 'valeo.com' },
    { name: 'ArcelorMittal', domain: 'arcelormittal.com' },
    { name: 'Alstom', domain: 'alstom.com' },
    { name: 'Nexans', domain: 'nexans.com' },
    { name: 'Daher', domain: 'daher.com' },
    { name: 'Dassault Aviation', domain: 'dassault-aviation.com' },
    { name: 'Naval Group', domain: 'naval-group.com' },
    { name: 'Bosch France', domain: 'bosch.fr' },
    { name: 'Siemens France', domain: 'siemens.fr' },
    { name: 'SKF France', domain: 'skf.com' },
    { name: 'Forvia', domain: 'forvia.com' },
    { name: 'Constellium', domain: 'constellium.com' },
    { name: 'Imerys', domain: 'imerys.com' },
    { name: 'Vallourec', domain: 'vallourec.com' },
    { name: 'Sika France', domain: 'sika.fr' },
    { name: 'Lafarge', domain: 'lafarge.fr' },
    // ETI et PMI
    { name: 'Mecachrome', domain: 'mecachrome.com' },
    { name: 'Lisi Group', domain: 'lisi-group.com' },
    { name: 'Radiall', domain: 'radiall.com' },
    { name: 'Somfy', domain: 'somfy.fr' },
    { name: 'Assa Abloy France', domain: 'assaabloy.fr' },
    { name: 'Armor', domain: 'armor-group.com' },
    { name: 'Manutan', domain: 'manutan.fr' },
    { name: 'Hager Group', domain: 'hagergroup.com' },
    { name: 'Crouzet', domain: 'crouzet.com' },
    { name: 'Texelis', domain: 'texelis.com' },
  ],

  'Automobile': [
    { name: 'Renault', domain: 'renault.fr' },
    { name: 'Stellantis', domain: 'stellantis.com' },
    { name: 'Norauto', domain: 'norauto.fr' },
    { name: 'Midas', domain: 'midas.fr' },
    { name: 'Speedy', domain: 'speedy.fr' },
    { name: 'Feu Vert', domain: 'feu-vert.fr' },
    { name: 'Euromaster', domain: 'euromaster.fr' },
    { name: 'Dekra', domain: 'dekra.fr' },
    { name: 'ALD Automotive', domain: 'aldautomotive.fr' },
    { name: 'Arval', domain: 'arval.fr' },
    { name: 'Toyota France', domain: 'toyota.fr' },
    { name: 'BMW France', domain: 'bmw.fr' },
    { name: 'Mercedes France', domain: 'mercedes-benz.fr' },
    { name: 'Peugeot', domain: 'peugeot.fr' },
    { name: 'Citroën', domain: 'citroen.fr' },
    { name: 'Dacia', domain: 'dacia.fr' },
    { name: 'Carglass', domain: 'carglass.fr' },
    { name: 'Autosphere', domain: 'autosphere.fr' },
    { name: 'Emil Frey', domain: 'emil-frey.fr' },
    { name: 'Aramis Auto', domain: 'aramisauto.com' },
    { name: 'Ford France', domain: 'ford.fr' },
    { name: 'Volkswagen France', domain: 'volkswagen.fr' },
    { name: 'Audi France', domain: 'audi.fr' },
    { name: 'Profil Plus', domain: 'profil-plus.fr' },
    { name: 'Point S', domain: 'point-s.fr' },
    { name: 'Vulco', domain: 'vulco.fr' },
    { name: 'AD Carrosserie', domain: 'ad.fr' },
    { name: 'Opteven', domain: 'opteven.com' },
    { name: 'Leasys', domain: 'leasys.com' },
    { name: 'Fraikin', domain: 'fraikin.fr' },
  ],

  'BTP / Construction': [
    { name: 'Vinci Construction', domain: 'vinci-construction.fr' },
    { name: 'Bouygues Construction', domain: 'bouygues-construction.com' },
    { name: 'Eiffage', domain: 'eiffage.com' },
    { name: 'NGE', domain: 'nge.fr' },
    { name: 'Colas', domain: 'colas.fr' },
    { name: 'Eurovia', domain: 'eurovia.com' },
    { name: 'Apave', domain: 'apave.com' },
    { name: 'Bureau Veritas', domain: 'bureauveritas.fr' },
    { name: 'Socotec', domain: 'socotec.fr' },
    { name: 'Egis', domain: 'egis.fr' },
    { name: 'Nexity', domain: 'nexity.fr' },
    { name: 'Bouygues Immobilier', domain: 'bouygues-immobilier.com' },
    { name: 'Fayat', domain: 'fayat.com' },
    { name: 'GSE', domain: 'gse.fr' },
    { name: 'Soprema', domain: 'soprema.fr' },
    { name: 'Mapei', domain: 'mapei.fr' },
    { name: 'Kaufman & Broad', domain: 'ketb.com' },
    { name: 'Léon Grosse', domain: 'leon-grosse.fr' },
    { name: 'Demathieu Bard', domain: 'demathieu-bard.fr' },
    { name: 'Razel-Bec', domain: 'razel-bec.com' },
    { name: 'Spie Batignolles', domain: 'spiebatignolles.fr' },
    { name: 'Setec', domain: 'setec.fr' },
    { name: 'Artelia', domain: 'arteliagroup.com' },
    { name: 'Freyssinet', domain: 'freyssinet.com' },
    { name: 'Chantiers Modernes', domain: 'vinci-construction.fr' },
    { name: 'GTM Bâtiment', domain: 'vinci-construction.fr' },
    { name: 'Quille Construction', domain: 'quille.fr' },
    { name: 'Bassac', domain: 'bassac.fr' },
    { name: 'Cogedim', domain: 'cogedim.com' },
    { name: 'Emerige', domain: 'emerige.fr' },
  ],

  'Logistique / Transport': [
    { name: 'Geodis', domain: 'geodis.com' },
    { name: 'XPO Logistics', domain: 'xpo.com' },
    { name: 'DB Schenker', domain: 'dbschenker.com' },
    { name: 'Kuehne Nagel', domain: 'kuehne-nagel.com' },
    { name: 'ID Logistics', domain: 'id-logistics.com' },
    { name: 'DHL France', domain: 'dhl.fr' },
    { name: 'Chronopost', domain: 'chronopost.fr' },
    { name: 'Mondial Relay', domain: 'mondialrelay.fr' },
    { name: 'FM Logistic', domain: 'fmlogistic.com' },
    { name: 'Bolloré Logistics', domain: 'bollore-logistics.com' },
    { name: 'CMA CGM', domain: 'cma-cgm.com' },
    { name: 'Transdev', domain: 'transdev.com' },
    { name: 'Keolis', domain: 'keolis.com' },
    { name: 'Heppner', domain: 'heppner.com' },
    { name: 'Dachser', domain: 'dachser.fr' },
    { name: 'Stef', domain: 'stef.com' },
    { name: 'Gefco', domain: 'gefco.net' },
    { name: 'Rhenus', domain: 'rhenus.fr' },
    { name: 'TNT France', domain: 'tnt.fr' },
    { name: 'Fedex France', domain: 'fedex.com' },
    { name: 'UPS France', domain: 'ups.com' },
    { name: 'La Poste Courrier', domain: 'laposte.fr' },
    { name: 'Colissimo', domain: 'colissimo.fr' },
    { name: 'Novatrans', domain: 'novatrans.fr' },
    { name: 'Ceva Logistics', domain: 'cevalogistics.com' },
    { name: 'Derichebourg Multiservices', domain: 'derichebourg.com' },
    { name: 'Norbert Dentressangle', domain: 'xpo.com' },
    { name: 'Kuehne + Nagel', domain: 'kuehne-nagel.com' },
    { name: 'Panalpina', domain: 'panalpina.com' },
    { name: 'Mory Ducros', domain: 'moryducros.fr' },
    { name: 'GLS France', domain: 'gls-france.com' },
    { name: 'Colissimo Pro', domain: 'colissimo.fr' },
    { name: 'Groupe Monnoyeur', domain: 'groupe-monnoyeur.com' },
    { name: 'Alloin', domain: 'alloin.fr' },
    { name: 'Combirail', domain: 'lohr.fr' },
  ],

  'Agroalimentaire': [
    { name: 'Danone', domain: 'danone.com' },
    { name: 'Lactalis', domain: 'lactalis.fr' },
    { name: 'Bigard', domain: 'bigard.fr' },
    { name: 'Savencia', domain: 'savencia.com' },
    { name: 'Bonduelle', domain: 'bonduelle.fr' },
    { name: 'Fleury Michon', domain: 'fleurymichon.fr' },
    { name: 'Cooperl', domain: 'cooperl.com' },
    { name: 'Bel', domain: 'groupe-bel.com' },
    { name: 'Sodiaal', domain: 'sodiaal.fr' },
    { name: 'Andros', domain: 'andros.fr' },
    { name: 'McCain France', domain: 'mccain.fr' },
    { name: 'Lindt', domain: 'lindt.fr' },
    { name: 'Ferrero France', domain: 'ferrero.fr' },
    { name: 'Mars France', domain: 'mars.com' },
    { name: 'Mondelez', domain: 'mondelezinternational.com' },
    { name: 'Haribo', domain: 'haribo.fr' },
    { name: 'Elle & Vire', domain: 'elle-vire.com' },
    { name: 'Candia', domain: 'candia.fr' },
    { name: 'Yoplait', domain: 'yoplait.fr' },
    { name: 'Panzani', domain: 'panzani.fr' },
    { name: 'Charal', domain: 'charal.fr' },
    { name: 'Herta', domain: 'herta.fr' },
    { name: 'William Saurin', domain: 'williamjames.fr' },
    { name: 'Bonduelle Fresh France', domain: 'bonduelle.fr' },
    { name: 'Pasquier', domain: 'groupepasquier.com' },
    { name: 'Harry\'s France', domain: 'harrys.fr' },
    { name: 'St Michel Biscuits', domain: 'biscuits-saint-michel.fr' },
    { name: 'Brioche Pasquier', domain: 'groupepasquier.com' },
    { name: 'Brossard', domain: 'brossard.fr' },
    { name: 'Tipiak', domain: 'tipiak.fr' },
    { name: 'Rians', domain: 'rians.fr' },
    { name: 'Entremont', domain: 'entremont.com' },
    { name: 'Elivia', domain: 'elivia.fr' },
    { name: 'Cofigeo', domain: 'cofigeo.fr' },
    { name: 'Lamb Weston', domain: 'lambweston.com' },
  ],

  'Retail / Commerce': [
    { name: 'Carrefour', domain: 'carrefour.fr' },
    { name: 'Leroy Merlin', domain: 'leroymerlin.fr' },
    { name: 'Decathlon', domain: 'decathlon.fr' },
    { name: 'Fnac Darty', domain: 'fnacdarty.com' },
    { name: 'Maisons du Monde', domain: 'maisonsdumonde.com' },
    { name: 'Ikea France', domain: 'ikea.com' },
    { name: 'Castorama', domain: 'castorama.fr' },
    { name: 'Brico Dépôt', domain: 'bricodepot.fr' },
    { name: 'Darty', domain: 'darty.com' },
    { name: 'Boulanger', domain: 'boulanger.com' },
    { name: 'Sephora', domain: 'sephora.fr' },
    { name: 'Yves Rocher', domain: 'yves-rocher.fr' },
    { name: "L'Occitane", domain: 'loccitane.com' },
    { name: 'Cultura', domain: 'cultura.com' },
    { name: 'Jules', domain: 'jules.com' },
    { name: 'Optic 2000', domain: 'optic2000.com' },
    { name: 'But', domain: 'but.fr' },
    { name: 'Conforama', domain: 'conforama.fr' },
    { name: 'King Jouet', domain: 'king-jouet.com' },
    { name: 'Kiabi', domain: 'kiabi.com' },
    { name: 'La Redoute', domain: 'laredoute.fr' },
    { name: 'Zara France', domain: 'zara.com' },
    { name: 'H&M France', domain: 'hm.com' },
    { name: 'Uniqlo France', domain: 'uniqlo.com' },
    { name: 'Mango France', domain: 'mango.com' },
    { name: 'Intersport', domain: 'intersport.fr' },
    { name: 'Go Sport', domain: 'go-sport.com' },
    { name: 'Cdiscount', domain: 'cdiscount.com' },
    { name: 'La Halle', domain: 'lahalle.com' },
    { name: 'Camaïeu', domain: 'camaieu.fr' },
    { name: 'Cyrillus', domain: 'cyrillus.fr' },
    { name: 'Jacadi', domain: 'jacadi.fr' },
    { name: 'Orchestra', domain: 'orchestra.fr' },
    { name: 'Tape à l\'Oeil', domain: 'tao.fr' },
    { name: 'Gémo', domain: 'gemo.fr' },
  ],

  'Services B2B': [
    { name: 'Sodexo', domain: 'sodexo.com' },
    { name: 'Edenred', domain: 'edenred.fr' },
    { name: 'Elior', domain: 'elior.com' },
    { name: 'Atalian', domain: 'atalian.fr' },
    { name: 'Onet', domain: 'onet.fr' },
    { name: 'Veolia', domain: 'veolia.fr' },
    { name: 'Engie', domain: 'engie.fr' },
    { name: 'TotalEnergies', domain: 'totalenergies.fr' },
    { name: 'Dalkia', domain: 'dalkia.fr' },
    { name: 'Spie', domain: 'spie.com' },
    { name: 'Axians', domain: 'axians.fr' },
    { name: 'Securitas', domain: 'securitas.fr' },
    { name: 'Prosegur', domain: 'prosegur.fr' },
    { name: 'Ortec', domain: 'ortec.fr' },
    { name: 'ISS France', domain: 'issworld.com' },
    { name: 'Compass Group', domain: 'compass-group.fr' },
    { name: 'Derichebourg', domain: 'derichebourg.com' },
    { name: 'Bouygues Energies', domain: 'bouygues-es.com' },
    { name: 'GTT', domain: 'gtt.fr' },
    { name: 'Thalès Services', domain: 'thalesgroup.com' },
    { name: 'Ineo', domain: 'ineo.com' },
    { name: 'Engie Solutions', domain: 'engie.fr' },
    { name: 'Samsic', domain: 'samsic.fr' },
    { name: 'Initial', domain: 'initial.fr' },
    { name: 'Rentokil', domain: 'rentokil.fr' },
    { name: 'Iss Facility Services', domain: 'issworld.com' },
    { name: 'Elis', domain: 'elis.com' },
    { name: 'De Backer', domain: 'debacker.fr' },
    { name: 'Vinci Facilities', domain: 'vinci.com' },
    { name: 'Idex', domain: 'idex.fr' },
  ],

  'Tech / Numérique': [
    { name: 'Capgemini', domain: 'capgemini.com' },
    { name: 'Sopra Steria', domain: 'soprasteria.com' },
    { name: 'Atos', domain: 'atos.net' },
    { name: 'CGI', domain: 'cgi.com' },
    { name: 'Wavestone', domain: 'wavestone.com' },
    { name: 'Accenture France', domain: 'accenture.com' },
    { name: 'IBM France', domain: 'ibm.com' },
    { name: 'SAP France', domain: 'sap.com' },
    { name: 'Microsoft France', domain: 'microsoft.com' },
    { name: 'Dassault Systèmes', domain: 'dassault-systemes.com' },
    { name: 'OVHcloud', domain: 'ovhcloud.com' },
    { name: 'Devoteam', domain: 'devoteam.com' },
    { name: 'Alten', domain: 'alten.fr' },
    { name: 'Cegid', domain: 'cegid.com' },
    { name: 'Generix Group', domain: 'generixgroup.com' },
    { name: 'Inetum', domain: 'inetum.com' },
    { name: 'Econocom', domain: 'econocom.com' },
    { name: 'Aubay', domain: 'aubay.com' },
    { name: 'Axway', domain: 'axway.com' },
    { name: 'Sage France', domain: 'sage.com' },
    { name: 'Talend', domain: 'talend.com' },
    { name: 'Criteo', domain: 'criteo.com' },
    { name: 'Blablacar', domain: 'blablacar.fr' },
    { name: 'Doctolib', domain: 'doctolib.fr' },
    { name: 'Qonto', domain: 'qonto.com' },
    { name: 'Payfit', domain: 'payfit.com' },
    { name: 'Contentsquare', domain: 'contentsquare.com' },
    { name: 'Mirakl', domain: 'mirakl.com' },
    { name: 'Deezer', domain: 'deezer.com' },
    { name: 'Dailymotion', domain: 'dailymotion.com' },
    { name: 'Vestiaire Collective', domain: 'vestiairecollective.com' },
    { name: 'Leboncoin', domain: 'leboncoin.fr' },
    { name: 'ManoMano', domain: 'manomano.fr' },
    { name: 'Luko', domain: 'luko.eu' },
    { name: 'Alan', domain: 'alan.com' },
  ],

  'Santé / Pharma': [
    { name: 'Sanofi', domain: 'sanofi.com' },
    { name: 'Pierre Fabre', domain: 'pierre-fabre.com' },
    { name: 'Ipsen', domain: 'ipsen.com' },
    { name: 'Servier', domain: 'servier.fr' },
    { name: 'Biomérieux', domain: 'biomerieux.fr' },
    { name: 'Boiron', domain: 'boiron.fr' },
    { name: 'Urgo', domain: 'urgo.fr' },
    { name: 'Coloplast', domain: 'coloplast.fr' },
    { name: 'Roche France', domain: 'roche.fr' },
    { name: 'Novartis France', domain: 'novartis.fr' },
    { name: 'Pfizer France', domain: 'pfizer.fr' },
    { name: 'AstraZeneca France', domain: 'astrazeneca.fr' },
    { name: 'Abbvie France', domain: 'abbvie.fr' },
    { name: 'Gilead France', domain: 'gilead.fr' },
    { name: 'Takeda France', domain: 'takeda.com' },
    { name: 'UCB Pharma', domain: 'ucb.com' },
    { name: 'Arkopharma', domain: 'arkopharma.fr' },
    { name: 'Guerbet', domain: 'guerbet.com' },
    { name: 'Fresenius', domain: 'fresenius.fr' },
    { name: 'B. Braun', domain: 'bbraun.fr' },
    { name: 'Hartmann', domain: 'hartmann.fr' },
    { name: 'Medtronic France', domain: 'medtronic.fr' },
    { name: 'Johnson & Johnson France', domain: 'jnj.com' },
    { name: 'Abbott France', domain: 'abbott.fr' },
    { name: 'Stryker France', domain: 'stryker.com' },
    { name: 'Zimmer Biomet', domain: 'zimmerbiomet.com' },
    { name: 'Essilor', domain: 'essilor.fr' },
    { name: 'Eurofins', domain: 'eurofins.fr' },
    { name: 'Cerba Healthcare', domain: 'cerba-healthcare.com' },
    { name: 'Ramsay Santé', domain: 'ramsay-sante.fr' },
  ],

  'Finance / Banque': [
    { name: 'BNP Paribas', domain: 'bnpparibas.fr' },
    { name: 'Société Générale', domain: 'societegenerale.fr' },
    { name: 'Crédit Agricole', domain: 'credit-agricole.fr' },
    { name: 'Crédit Mutuel', domain: 'creditmutuel.fr' },
    { name: 'La Banque Postale', domain: 'labanquepostale.fr' },
    { name: "Caisse d'Épargne", domain: 'caisse-epargne.fr' },
    { name: 'Banque Populaire', domain: 'banquepopulaire.fr' },
    { name: 'AXA France', domain: 'axa.fr' },
    { name: 'Allianz France', domain: 'allianz.fr' },
    { name: 'Groupama', domain: 'groupama.fr' },
    { name: 'Natixis', domain: 'natixis.com' },
    { name: 'Amundi', domain: 'amundi.fr' },
    { name: 'Malakoff Humanis', domain: 'malakoffhumanis.fr' },
    { name: 'Generali France', domain: 'generali.fr' },
    { name: 'Maif', domain: 'maif.fr' },
    { name: 'Macif', domain: 'macif.fr' },
    { name: 'LCL', domain: 'lcl.fr' },
    { name: 'CIC', domain: 'cic.fr' },
    { name: 'Boursorama', domain: 'boursorama.com' },
    { name: 'April', domain: 'april.fr' },
    { name: 'Covéa', domain: 'covea.fr' },
    { name: 'SwissLife France', domain: 'swisslife.fr' },
    { name: 'CNP Assurances', domain: 'cnp.fr' },
    { name: 'Cardif', domain: 'cardif.fr' },
    { name: 'Crédit Foncier', domain: 'creditfoncier.fr' },
    { name: 'Crédit Immobilier de France', domain: 'credit-immobilier-de-france.fr' },
    { name: 'Arkéa', domain: 'arkea.com' },
    { name: 'Crédit du Nord', domain: 'credit-du-nord.fr' },
    { name: 'Fortuneo', domain: 'fortuneo.fr' },
    { name: 'ING Direct France', domain: 'ing.fr' },
  ],

  'Immobilier': [
    { name: 'Nexity', domain: 'nexity.fr' },
    { name: 'Orpi', domain: 'orpi.com' },
    { name: 'Century 21', domain: 'century21.fr' },
    { name: 'Era Immobilier', domain: 'era-immobilier.fr' },
    { name: 'Guy Hoquet', domain: 'guy-hoquet.com' },
    { name: 'Laforêt', domain: 'laforet.com' },
    { name: 'Foncia', domain: 'foncia.com' },
    { name: 'Citya', domain: 'citya.com' },
    { name: 'Icade', domain: 'icade.fr' },
    { name: 'Altarea', domain: 'altarea.com' },
    { name: 'Gecina', domain: 'gecina.fr' },
    { name: 'Covivio', domain: 'covivio.eu' },
    { name: 'Primonial', domain: 'primonial.fr' },
    { name: 'Vinci Immobilier', domain: 'vinci-immobilier.com' },
    { name: 'Eiffage Immobilier', domain: 'eiffage-immobilier.com' },
    { name: 'Cogedim', domain: 'cogedim.com' },
    { name: 'Bassac', domain: 'bassac.fr' },
    { name: 'Sergic', domain: 'sergic.fr' },
    { name: 'Sogeprom', domain: 'sogeprom.fr' },
    { name: 'CDC Habitat', domain: 'cdchabitat.fr' },
    { name: 'Paris Habitat', domain: 'parishabitat.fr' },
    { name: 'SNI', domain: 'sni.fr' },
    { name: 'Efidis', domain: 'efidis.fr' },
    { name: 'Immobilière 3F', domain: 'immobiliere3f.fr' },
    { name: 'Logirep', domain: 'logirep.fr' },
  ],

  'Hôtellerie / Restauration': [
    { name: 'Accor', domain: 'accor.com' },
    { name: 'Louvre Hotels', domain: 'louvrehotels.com' },
    { name: 'B&B Hotels', domain: 'hotel-bb.com' },
    { name: 'Marriott France', domain: 'marriott.fr' },
    { name: 'Hilton France', domain: 'hilton.com' },
    { name: "McDonald's France", domain: 'mcdonalds.fr' },
    { name: 'Burger King France', domain: 'burgerking.fr' },
    { name: 'KFC France', domain: 'kfc.fr' },
    { name: "Domino's Pizza", domain: 'dominos.fr' },
    { name: 'Flunch', domain: 'flunch.fr' },
    { name: 'Courtepaille', domain: 'courtepaille.com' },
    { name: 'Areas', domain: 'areas.com' },
    { name: 'Newrest', domain: 'newrest.eu' },
    { name: 'Elior', domain: 'elior.com' },
    { name: 'Sodexo', domain: 'sodexo.com' },
    { name: 'Ibis', domain: 'ibis.com' },
    { name: 'Novotel', domain: 'novotel.com' },
    { name: 'Mercure', domain: 'mercure.com' },
    { name: 'Hyatt France', domain: 'hyatt.com' },
    { name: 'Four Seasons France', domain: 'fourseasons.com' },
    { name: 'Relais & Châteaux', domain: 'relaischateaux.com' },
    { name: 'Groupe Flo', domain: 'groupeflo.fr' },
    { name: 'Hippopotamus', domain: 'hippopotamus.fr' },
    { name: 'Buffalo Grill', domain: 'buffalo-grill.fr' },
    { name: 'La Mie Câline', domain: 'lamiecaline.com' },
    { name: 'Paul', domain: 'paul.fr' },
    { name: 'Brioche Dorée', domain: 'briochedoree.fr' },
    { name: 'Eat Salad', domain: 'eatsalad.com' },
    { name: 'Léon de Bruxelles', domain: 'leon-de-bruxelles.fr' },
    { name: 'Campanile', domain: 'campanile.com' },
  ],

  'Éducation / Formation': [
    { name: 'Groupe IGS', domain: 'groupe-igs.fr' },
    { name: 'Groupe INSEEC', domain: 'inseec.com' },
    { name: 'KEDGE Business School', domain: 'kedge.edu' },
    { name: 'SKEMA', domain: 'skema.edu' },
    { name: 'EDHEC', domain: 'edhec.edu' },
    { name: 'EM Lyon', domain: 'emlyon.com' },
    { name: 'Grenoble EM', domain: 'grenoble-em.com' },
    { name: 'Cesi', domain: 'cesi.fr' },
    { name: 'Afpa', domain: 'afpa.fr' },
    { name: 'OpenClassrooms', domain: 'openclassrooms.com' },
    { name: 'Studi', domain: 'studi.fr' },
    { name: 'Cegos', domain: 'cegos.fr' },
    { name: 'Demos', domain: 'demos.fr' },
    { name: 'Pigier', domain: 'pigier.com' },
    { name: 'Abilways', domain: 'abilways.fr' },
    { name: 'HEC Paris', domain: 'hec.edu' },
    { name: 'ESSEC', domain: 'essec.edu' },
    { name: 'ESCP', domain: 'escp.eu' },
    { name: 'Ionis Education', domain: 'ionis-education-group.com' },
    { name: 'ESIEE Paris', domain: 'esiee.fr' },
    { name: 'Centrale Supélec', domain: 'centralesupelec.fr' },
    { name: 'Montpellier Business School', domain: 'montpellier-bs.com' },
    { name: 'ICN Business School', domain: 'icn-artem.com' },
    { name: 'Excelia Group', domain: 'excelia-group.com' },
    { name: 'Institut Limayrac', domain: 'limayrac.fr' },
    { name: 'Formaposte', domain: 'formaposte.fr' },
    { name: 'CCI Formation', domain: 'cci.fr' },
    { name: 'Greta', domain: 'greta.fr' },
    { name: 'M2i Formation', domain: 'm2iformation.fr' },
    { name: 'Orsys', domain: 'orsys.fr' },
  ],

  'Énergie / Environnement': [
    { name: 'EDF', domain: 'edf.fr' },
    { name: 'Engie', domain: 'engie.fr' },
    { name: 'TotalEnergies', domain: 'totalenergies.fr' },
    { name: 'Veolia', domain: 'veolia.fr' },
    { name: 'Suez', domain: 'suez.com' },
    { name: 'Enedis', domain: 'enedis.fr' },
    { name: 'GRTgaz', domain: 'grtgaz.com' },
    { name: 'GRDF', domain: 'grdf.fr' },
    { name: 'RTE', domain: 'rte-france.com' },
    { name: 'Voltalia', domain: 'voltalia.com' },
    { name: 'Neoen', domain: 'neoen.com' },
    { name: 'Akuo Energy', domain: 'akuo.energy' },
    { name: 'Boralex', domain: 'boralex.com' },
    { name: 'Engie Green', domain: 'engie-green.fr' },
    { name: 'EDF Renouvelables', domain: 'edf-renouvelables.com' },
    { name: 'Paprec', domain: 'paprec.com' },
    { name: 'Séché Environnement', domain: 'groupe-seche.com' },
    { name: 'Saur', domain: 'saur.fr' },
    { name: 'Dalkia', domain: 'dalkia.fr' },
    { name: 'Idex', domain: 'idex.fr' },
    { name: 'Storengy', domain: 'storengy.com' },
    { name: 'Valorem', domain: 'valorem.fr' },
    { name: 'Vattenfall France', domain: 'vattenfall.fr' },
    { name: 'Eolfi', domain: 'eolfi.com' },
    { name: 'Inéo', domain: 'ineo.com' },
    { name: 'Veolia Eau', domain: 'veolia.fr' },
    { name: 'Suez Eau France', domain: 'suez.com' },
    { name: 'Lyonnaise des Eaux', domain: 'lyonnaise-des-eaux.fr' },
    { name: 'Ortec Environnement', domain: 'ortec.fr' },
    { name: 'Veolia Propreté', domain: 'veolia.fr' },
  ],

  'Ressources Humaines': [
    { name: 'Manpower', domain: 'manpower.fr' },
    { name: 'Adecco', domain: 'adecco.fr' },
    { name: 'Randstad', domain: 'randstad.fr' },
    { name: 'Michael Page', domain: 'michaelpage.fr' },
    { name: 'Robert Half', domain: 'roberthalf.fr' },
    { name: 'Hays France', domain: 'hays.fr' },
    { name: 'Page Personnel', domain: 'pagepersonnel.fr' },
    { name: 'Fed Group', domain: 'fedgroup.fr' },
    { name: 'Expectra', domain: 'expectra.fr' },
    { name: 'Synergie', domain: 'synergie.fr' },
    { name: 'Proman', domain: 'proman.fr' },
    { name: 'Groupe Crit', domain: 'groupecrit.fr' },
    { name: 'Adequat', domain: 'adequat-emploi.com' },
    { name: 'Actual Group', domain: 'actual.fr' },
    { name: 'Nexus', domain: 'nexus.fr' },
    { name: 'Partnaire', domain: 'partnaire.fr' },
    { name: 'Gi Group', domain: 'gigroup.fr' },
    { name: 'Kelly Services', domain: 'kellyservices.fr' },
    { name: 'Start People', domain: 'startpeople.fr' },
    { name: 'Cegid Talent', domain: 'cegid.com' },
    { name: 'Payfit', domain: 'payfit.com' },
    { name: 'Lucca', domain: 'lucca.fr' },
    { name: 'Altedia', domain: 'altedia.fr' },
    { name: 'BPI Group', domain: 'bpigroup.fr' },
    { name: 'Mercer France', domain: 'mercer.fr' },
    { name: 'Towers Watson', domain: 'willistowerswatson.com' },
    { name: 'Aon Hewitt', domain: 'aon.fr' },
    { name: 'Spencer Stuart', domain: 'spencerstuart.com' },
    { name: 'Korn Ferry', domain: 'kornferry.com' },
    { name: 'Boyden France', domain: 'boyden.com' },
  ],

  'Conseil / Audit': [
    { name: 'Deloitte France', domain: 'deloitte.fr' },
    { name: 'PwC France', domain: 'pwc.fr' },
    { name: 'KPMG France', domain: 'kpmg.fr' },
    { name: 'EY France', domain: 'ey.com' },
    { name: 'McKinsey France', domain: 'mckinsey.com' },
    { name: 'BCG France', domain: 'bcg.com' },
    { name: 'Bain France', domain: 'bain.com' },
    { name: 'Roland Berger', domain: 'rolandberger.com' },
    { name: 'Oliver Wyman', domain: 'oliverwyman.com' },
    { name: 'AT Kearney', domain: 'kearney.com' },
    { name: 'Mazars', domain: 'mazars.fr' },
    { name: 'Grant Thornton', domain: 'grantthornton.fr' },
    { name: 'BDO France', domain: 'bdo.fr' },
    { name: 'Accuracy', domain: 'accuracy.com' },
    { name: 'Eight Advisory', domain: 'eight-advisory.com' },
    { name: 'Sia Partners', domain: 'sia-partners.com' },
    { name: 'Colombus Consulting', domain: 'colombus-consulting.com' },
    { name: 'Onepoint', domain: 'groupeonepoint.com' },
    { name: 'Wavestone', domain: 'wavestone.com' },
    { name: 'Kurt Salmon', domain: 'kurtsalmon.com' },
    { name: 'Ailancy', domain: 'ailancy.com' },
    { name: 'Advolis', domain: 'advolis.com' },
    { name: 'Vertuo Conseil', domain: 'vertuo-conseil.fr' },
    { name: 'Citwell', domain: 'citwell.com' },
    { name: 'Argon & Co', domain: 'argonco.com' },
    { name: 'Square Management', domain: 'squaremanagement.fr' },
    { name: 'Kea & Partners', domain: 'kea-partners.com' },
    { name: 'Bearing Point', domain: 'bearingpoint.com' },
    { name: 'Capco France', domain: 'capco.com' },
    { name: 'Tallis Consulting', domain: 'tallis-consulting.com' },
  ],

  'Médias / Communication': [
    { name: 'TF1 Group', domain: 'tf1.fr' },
    { name: 'France Télévisions', domain: 'francetelevisions.fr' },
    { name: 'M6 Group', domain: 'm6.fr' },
    { name: 'Canal+', domain: 'canalplus.com' },
    { name: 'Radio France', domain: 'radiofrance.fr' },
    { name: 'RTL Group', domain: 'rtl.fr' },
    { name: 'Le Monde', domain: 'lemonde.fr' },
    { name: 'Le Figaro', domain: 'lefigaro.fr' },
    { name: 'Publicis', domain: 'publicisgroupe.com' },
    { name: 'Havas', domain: 'havas.com' },
    { name: 'BETC', domain: 'betc.com' },
    { name: 'Ogilvy France', domain: 'ogilvy.com' },
    { name: 'McCann France', domain: 'mccann.fr' },
    { name: 'TBWA France', domain: 'tbwa.fr' },
    { name: 'Kantar France', domain: 'kantar.com' },
    { name: 'Ipsos France', domain: 'ipsos.fr' },
    { name: 'Nielsen France', domain: 'nielsen.com' },
    { name: 'Prisma Media', domain: 'prismamedia.com' },
    { name: 'Europe 1', domain: 'europe1.fr' },
    { name: 'Libération', domain: 'liberation.fr' },
    { name: "L'Express", domain: 'lexpress.fr' },
    { name: 'Le Parisien', domain: 'leparisien.fr' },
    { name: 'Les Échos', domain: 'lesechos.fr' },
    { name: 'La Tribune', domain: 'latribune.fr' },
    { name: 'Ouest France', domain: 'ouest-france.fr' },
    { name: 'La Dépêche', domain: 'ladepeche.fr' },
    { name: 'Le Progrès', domain: 'leprogres.fr' },
    { name: 'Sud Ouest', domain: 'sudouest.fr' },
    { name: 'Altice Media', domain: 'altice.net' },
    { name: 'Reworld Media', domain: 'reworldmedia.com' },
  ],

};

// Filtre par ville/région pour prioriser les entreprises locales
function getCompaniesByRegion(secteur, ville, limit) {
  const toutes = DOMAINES_PAR_SECTEUR[secteur] || [];

  // Mapping ville → mots-clés domaine régionaux
  const regionMap = {
    'lyon': ['savoie', 'rhone', 'auvergne', 'lyon', 'grenoble'],
    'paris': ['paris', 'idf', 'ile-de-france', 'versailles'],
    'marseille': ['marseille', 'paca', 'provence', 'alpes'],
    'bordeaux': ['bordeaux', 'gironde', 'aquitaine'],
    'toulouse': ['toulouse', 'occitanie', 'midi'],
    'nantes': ['nantes', 'loire', 'bretagne', 'pays-de-la-loire'],
    'lille': ['lille', 'nordpasdecalais', 'hauts-de-france'],
    'strasbourg': ['strasbourg', 'alsace', 'grandest'],
    'nice': ['nice', 'coted azur', 'alpes-maritimes'],
    'montpellier': ['montpellier', 'herault', 'languedoc'],
    'rennes': ['rennes', 'bretagne', 'ille-et-vilaine'],
    'grenoble': ['grenoble', 'isere', 'alpes'],
  };

  const villeLower = (ville || '').toLowerCase();

  // Cherche si la ville correspond à une région connue
  let motsRegion = [];
  for (const [key, mots] of Object.entries(regionMap)) {
    if (villeLower.includes(key)) {
      motsRegion = mots;
      break;
    }
  }

  // Si région identifiée, priorise entreprises locales
  if (motsRegion.length > 0) {
    const locales = toutes.filter(c => 
      motsRegion.some(m => c.domain.includes(m) || c.name.toLowerCase().includes(m))
    );
    const autres = toutes.filter(c => 
      !motsRegion.some(m => c.domain.includes(m) || c.name.toLowerCase().includes(m))
    );
    return [...locales, ...autres].slice(0, limit);
  }

  return toutes.slice(0, limit);
}

module.exports = { DOMAINES_PAR_SECTEUR, getCompaniesByRegion };
