// api/companies.js — Base de données enrichie 1500+ entreprises françaises

const DOMAINES_PAR_SECTEUR = {

  'Distribution / Négoce': [
    { name: 'Sysco France', domain: 'sysco.fr' },
    { name: 'Metro France', domain: 'metro.fr' },
    { name: 'Pomona', domain: 'pomona.fr' },
    { name: 'Transgourmet', domain: 'transgourmet.fr' },
    { name: 'Brake France', domain: 'brake.fr' },
    { name: 'Pro à Pro', domain: 'proapro.fr' },
    { name: 'Promocash', domain: 'promocash.fr' },
    { name: 'Agrial', domain: 'agrial.fr' },
    { name: 'Euralis', domain: 'euralis.fr' },
    { name: 'Biocoop', domain: 'biocoop.fr' },
    { name: 'Leclerc', domain: 'e.leclerc' },
    { name: 'Intermarché', domain: 'intermarche.com' },
    { name: 'Lidl France', domain: 'lidl.fr' },
    { name: 'Aldi France', domain: 'aldi.fr' },
    { name: 'Picard Surgelés', domain: 'picard.fr' },
    { name: 'Labeyrie', domain: 'labeyrie.fr' },
    { name: 'Maïsadour', domain: 'maisadour.com' },
    { name: 'Arterris', domain: 'arterris.fr' },
    { name: 'Terrena', domain: 'terrena.fr' },
    { name: 'InVivo', domain: 'invivo-group.com' },
    { name: 'Vivescia', domain: 'vivescia.com' },
    { name: 'Limagrain', domain: 'limagrain.com' },
    { name: 'Soufflet', domain: 'soufflet.com' },
    { name: 'Axéréal', domain: 'axereal.com' },
    { name: 'PassionFroid', domain: 'passionfroid.fr' },
    { name: 'TerreAzur', domain: 'terreazur.com' },
    { name: 'Socopa', domain: 'socopa.fr' },
    { name: 'Groupe Roullier', domain: 'roullier.com' },
    { name: 'Lur Berri', domain: 'lurberri.fr' },
    { name: 'Gamm Vert', domain: 'gammvert.fr' },
    { name: 'Truffaut', domain: 'truffaut.com' },
    { name: 'Tollens', domain: 'tollens.com' },
    { name: 'Point P', domain: 'pointp.fr' },
    { name: 'Saint-Gobain Distribution', domain: 'sgdbfrance.fr' },
    { name: 'Rexel', domain: 'rexel.fr' },
    { name: 'Sonepar', domain: 'sonepar.fr' },
    { name: 'Würth France', domain: 'wurth.fr' },
    { name: 'Brossette', domain: 'brossette.fr' },
    { name: 'Descours & Cabaud', domain: 'descours-cabaud.com' },
    { name: 'Lapeyre', domain: 'lapeyre.fr' },
  ],

  'Industrie': [
    { name: 'Schneider Electric', domain: 'se.com' },
    { name: 'Saint-Gobain', domain: 'saint-gobain.com' },
    { name: 'Faurecia', domain: 'faurecia.com' },
    { name: 'Legrand', domain: 'legrand.fr' },
    { name: 'Plastic Omnium', domain: 'plasticomnium.com' },
    { name: 'Safran', domain: 'safran-group.com' },
    { name: 'Thales', domain: 'thalesgroup.com' },
    { name: 'Airbus', domain: 'airbus.com' },
    { name: 'Michelin', domain: 'michelin.fr' },
    { name: 'Valeo', domain: 'valeo.com' },
    { name: 'ArcelorMittal', domain: 'arcelormittal.com' },
    { name: 'Alstom', domain: 'alstom.com' },
    { name: 'Nexans', domain: 'nexans.com' },
    { name: 'Daher', domain: 'daher.com' },
    { name: 'Dassault Aviation', domain: 'dassault-aviation.com' },
    { name: 'Naval Group', domain: 'naval-group.com' },
    { name: 'Bosch France', domain: 'bosch.fr' },
    { name: 'Siemens France', domain: 'siemens.fr' },
    { name: 'Forvia', domain: 'forvia.com' },
    { name: 'Constellium', domain: 'constellium.com' },
    { name: 'Imerys', domain: 'imerys.com' },
    { name: 'Vallourec', domain: 'vallourec.com' },
    { name: 'Sika France', domain: 'sika.fr' },
    { name: 'Lafarge', domain: 'lafarge.fr' },
    { name: 'Mecachrome', domain: 'mecachrome.com' },
    { name: 'Lisi Group', domain: 'lisi-group.com' },
    { name: 'Radiall', domain: 'radiall.com' },
    { name: 'Somfy', domain: 'somfy.fr' },
    { name: 'Manutan', domain: 'manutan.fr' },
    { name: 'Hager Group', domain: 'hagergroup.com' },
    { name: 'Texelis', domain: 'texelis.com' },
    { name: 'Groupe Lapeyre', domain: 'lapeyre.fr' },
    { name: 'Cetim', domain: 'cetim.fr' },
    { name: 'Hutchinson', domain: 'hutchinson.com' },
    { name: 'Parker Hannifin France', domain: 'parker.com' },
    { name: 'ITT Industries France', domain: 'itt.com' },
    { name: 'Staubli', domain: 'staubli.com' },
    { name: 'Komax France', domain: 'komax.com' },
    { name: 'Silgan Dispensing', domain: 'silgan.com' },
    { name: 'Fives Group', domain: 'fivesgroup.com' },
    { name: 'Kuhn', domain: 'kuhn.fr' },
    { name: 'Claas France', domain: 'claas.fr' },
    { name: 'John Deere France', domain: 'deere.fr' },
    { name: 'Manitou', domain: 'manitou.com' },
    { name: 'Bobcat France', domain: 'bobcat.fr' },
  ],

  'Automobile': [
    { name: 'Renault', domain: 'renault.fr' },
    { name: 'Stellantis', domain: 'stellantis.com' },
    { name: 'Norauto', domain: 'norauto.fr' },
    { name: 'Midas', domain: 'midas.fr' },
    { name: 'Speedy', domain: 'speedy.fr' },
    { name: 'Feu Vert', domain: 'feu-vert.fr' },
    { name: 'Euromaster', domain: 'euromaster.fr' },
    { name: 'Dekra', domain: 'dekra.fr' },
    { name: 'ALD Automotive', domain: 'aldautomotive.fr' },
    { name: 'Arval', domain: 'arval.fr' },
    { name: 'Toyota France', domain: 'toyota.fr' },
    { name: 'BMW France', domain: 'bmw.fr' },
    { name: 'Mercedes France', domain: 'mercedes-benz.fr' },
    { name: 'Carglass', domain: 'carglass.fr' },
    { name: 'Autosphere', domain: 'autosphere.fr' },
    { name: 'Emil Frey', domain: 'emil-frey.fr' },
    { name: 'Aramis Auto', domain: 'aramisauto.com' },
    { name: 'Profil Plus', domain: 'profil-plus.fr' },
    { name: 'Point S', domain: 'point-s.fr' },
    { name: 'Vulco', domain: 'vulco.fr' },
    { name: 'Opteven', domain: 'opteven.com' },
    { name: 'Leasys', domain: 'leasys.com' },
    { name: 'Fraikin', domain: 'fraikin.fr' },
    { name: 'LeasePlan France', domain: 'leaseplan.fr' },
    { name: 'Vivo Energy France', domain: 'vivoenergy.com' },
    { name: 'Entrepôt Auto', domain: 'entrepot-auto.fr' },
    { name: 'Autodis Group', domain: 'autodis-group.com' },
    { name: 'Alliance Automotive', domain: 'allianceautomotive.fr' },
    { name: 'AD Parts', domain: 'ad.fr' },
    { name: 'Oscaro', domain: 'oscaro.com' },
  ],

  'BTP / Construction': [
    { name: 'Vinci Construction', domain: 'vinci-construction.fr' },
    { name: 'Bouygues Construction', domain: 'bouygues-construction.com' },
    { name: 'Eiffage', domain: 'eiffage.com' },
    { name: 'NGE', domain: 'nge.fr' },
    { name: 'Colas', domain: 'colas.fr' },
    { name: 'Eurovia', domain: 'eurovia.com' },
    { name: 'Apave', domain: 'apave.com' },
    { name: 'Bureau Veritas', domain: 'bureauveritas.fr' },
    { name: 'Socotec', domain: 'socotec.fr' },
    { name: 'Egis', domain: 'egis.fr' },
    { name: 'Nexity', domain: 'nexity.fr' },
    { name: 'Bouygues Immobilier', domain: 'bouygues-immobilier.com' },
    { name: 'Fayat', domain: 'fayat.com' },
    { name: 'GSE', domain: 'gse.fr' },
    { name: 'Soprema', domain: 'soprema.fr' },
    { name: 'Kaufman & Broad', domain: 'ketb.com' },
    { name: 'Léon Grosse', domain: 'leon-grosse.fr' },
    { name: 'Demathieu Bard', domain: 'demathieu-bard.fr' },
    { name: 'Razel-Bec', domain: 'razel-bec.com' },
    { name: 'Spie Batignolles', domain: 'spiebatignolles.fr' },
    { name: 'Setec', domain: 'setec.fr' },
    { name: 'Artelia', domain: 'arteliagroup.com' },
    { name: 'Freyssinet', domain: 'freyssinet.com' },
    { name: 'Quille Construction', domain: 'quille.fr' },
    { name: 'Cogedim', domain: 'cogedim.com' },
    { name: 'Emerige', domain: 'emerige.fr' },
    { name: 'Spie', domain: 'spie.com' },
    { name: 'GTM Construction', domain: 'vinci-construction.fr' },
    { name: 'Besix France', domain: 'besix.com' },
    { name: 'Kier France', domain: 'kier.fr' },
    { name: 'Spie Sud-Est', domain: 'spie.com' },
    { name: 'Guintoli', domain: 'guintoli.com' },
    { name: 'Jean Lefebvre', domain: 'eurovia.com' },
    { name: 'Gerland Construction', domain: 'gerland.fr' },
    { name: 'Brezillon', domain: 'brezillon.fr' },
    { name: 'Sogea-Satom', domain: 'sogeaatom.com' },
    { name: 'Tarmac France', domain: 'tarmac.fr' },
    { name: 'Cemex France', domain: 'cemex.fr' },
    { name: 'Lafarge Holcim', domain: 'lafargeholcim.fr' },
    { name: 'Vicat', domain: 'vicat.fr' },
  ],

  'Logistique / Transport': [
    { name: 'Geodis', domain: 'geodis.com' },
    { name: 'XPO Logistics', domain: 'xpo.com' },
    { name: 'DB Schenker', domain: 'dbschenker.com' },
    { name: 'Kuehne Nagel', domain: 'kuehne-nagel.com' },
    { name: 'ID Logistics', domain: 'id-logistics.com' },
    { name: 'FM Logistic', domain: 'fmlogistic.com' },
    { name: 'Bolloré Logistics', domain: 'bollore-logistics.com' },
    { name: 'CMA CGM', domain: 'cma-cgm.com' },
    { name: 'Transdev', domain: 'transdev.com' },
    { name: 'Keolis', domain: 'keolis.com' },
    { name: 'Heppner', domain: 'heppner.com' },
    { name: 'Dachser', domain: 'dachser.fr' },
    { name: 'Stef', domain: 'stef.com' },
    { name: 'Gefco', domain: 'gefco.net' },
    { name: 'Rhenus', domain: 'rhenus.fr' },
    { name: 'Ceva Logistics', domain: 'cevalogistics.com' },
    { name: 'Derichebourg Multiservices', domain: 'derichebourg.com' },
    { name: 'GLS France', domain: 'gls-france.com' },
    { name: 'Groupe Monnoyeur', domain: 'groupe-monnoyeur.com' },
    { name: 'Alloin', domain: 'alloin.fr' },
    { name: 'Novatrans', domain: 'novatrans.fr' },
    { name: 'Mondial Relay', domain: 'mondialrelay.fr' },
    { name: 'Colissimo', domain: 'colissimo.fr' },
    { name: 'Intermarché Transport', domain: 'mousquetaires.com' },
    { name: 'Norbert Dentressangle', domain: 'xpo.com' },
    { name: 'Fleuriot Fleurs', domain: 'fleuriot.com' },
    { name: 'Groupe CAT', domain: 'groupe-cat.com' },
    { name: 'GT Logistics', domain: 'gt-logistics.fr' },
    { name: 'Sittex', domain: 'sittex.fr' },
    { name: 'Rexnord Logistic', domain: 'rexnord.com' },
    { name: 'Graveleau', domain: 'graveleau.fr' },
    { name: 'Prologis France', domain: 'prologis.com' },
    { name: 'Argan', domain: 'argan.fr' },
    { name: 'Lidl Logistique', domain: 'lidl.fr' },
    { name: 'Amazon Logistics', domain: 'amazon.fr' },
    { name: 'Chronofresh', domain: 'chronofresh.fr' },
    { name: 'Cargomatic', domain: 'cargomatic.fr' },
    { name: 'Shippeo', domain: 'shippeo.com' },
    { name: 'Clasquin', domain: 'clasquin.com' },
    { name: 'SDV Logistics', domain: 'bollore-logistics.com' },
  ],

  'Agroalimentaire': [
    { name: 'Danone', domain: 'danone.com' },
    { name: 'Lactalis', domain: 'lactalis.fr' },
    { name: 'Bigard', domain: 'bigard.fr' },
    { name: 'Savencia', domain: 'savencia.com' },
    { name: 'Bonduelle', domain: 'bonduelle.fr' },
    { name: 'Fleury Michon', domain: 'fleurymichon.fr' },
    { name: 'Cooperl', domain: 'cooperl.com' },
    { name: 'Bel', domain: 'groupe-bel.com' },
    { name: 'Sodiaal', domain: 'sodiaal.fr' },
    { name: 'Andros', domain: 'andros.fr' },
    { name: 'McCain France', domain: 'mccain.fr' },
    { name: 'Lindt', domain: 'lindt.fr' },
    { name: 'Ferrero France', domain: 'ferrero.fr' },
    { name: 'Elle & Vire', domain: 'elle-vire.com' },
    { name: 'Panzani', domain: 'panzani.fr' },
    { name: 'Charal', domain: 'charal.fr' },
    { name: 'Herta', domain: 'herta.fr' },
    { name: 'Pasquier', domain: 'groupepasquier.com' },
    { name: 'St Michel Biscuits', domain: 'biscuits-saint-michel.fr' },
    { name: 'Brossard', domain: 'brossard.fr' },
    { name: 'Tipiak', domain: 'tipiak.fr' },
    { name: 'Rians', domain: 'rians.fr' },
    { name: 'Entremont', domain: 'entremont.com' },
    { name: 'Elivia', domain: 'elivia.fr' },
    { name: 'Cofigeo', domain: 'cofigeo.fr' },
    { name: 'Groupe Avril', domain: 'groupe-avril.com' },
    { name: 'Tereos', domain: 'tereos.com' },
    { name: 'Cristal Union', domain: 'cristal-union.fr' },
    { name: 'Lesaffre', domain: 'lesaffre.com' },
    { name: 'Roquette', domain: 'roquette.com' },
    { name: 'Pernod Ricard France', domain: 'pernod-ricard.com' },
    { name: 'LVMH Moët Hennessy', domain: 'lvmh.fr' },
    { name: 'Rémy Cointreau', domain: 'remy-cointreau.com' },
    { name: 'Brasseries Kronenbourg', domain: 'kronenbourg.com' },
    { name: 'Heineken France', domain: 'heineken.fr' },
    { name: 'Orangina Schweppes', domain: 'orangina-schweppes.com' },
    { name: 'Coca-Cola France', domain: 'coca-cola.fr' },
    { name: 'Nestlé France', domain: 'nestle.fr' },
    { name: 'Unilever France', domain: 'unilever.fr' },
    { name: 'Procter & Gamble France', domain: 'pg.com' },
  ],

  'Retail / Commerce': [
    { name: 'Carrefour', domain: 'carrefour.fr' },
    { name: 'Leroy Merlin', domain: 'leroymerlin.fr' },
    { name: 'Decathlon', domain: 'decathlon.fr' },
    { name: 'Fnac Darty', domain: 'fnacdarty.com' },
    { name: 'Maisons du Monde', domain: 'maisonsdumonde.com' },
    { name: 'Ikea France', domain: 'ikea.com' },
    { name: 'Castorama', domain: 'castorama.fr' },
    { name: 'Brico Dépôt', domain: 'bricodepot.fr' },
    { name: 'Boulanger', domain: 'boulanger.com' },
    { name: 'Sephora', domain: 'sephora.fr' },
    { name: 'Yves Rocher', domain: 'yves-rocher.fr' },
    { name: 'Cultura', domain: 'cultura.com' },
    { name: 'Optic 2000', domain: 'optic2000.com' },
    { name: 'But', domain: 'but.fr' },
    { name: 'Conforama', domain: 'conforama.fr' },
    { name: 'Kiabi', domain: 'kiabi.com' },
    { name: 'La Redoute', domain: 'laredoute.fr' },
    { name: 'Intersport', domain: 'intersport.fr' },
    { name: 'Go Sport', domain: 'go-sport.com' },
    { name: 'Cdiscount', domain: 'cdiscount.com' },
    { name: 'Gémo', domain: 'gemo.fr' },
    { name: 'Brico Leclerc', domain: 'e.leclerc' },
    { name: 'Weldom', domain: 'weldom.com' },
    { name: 'Mr Bricolage', domain: 'mr-bricolage.fr' },
    { name: 'Bricorama', domain: 'bricorama.fr' },
    { name: 'Brico Marché', domain: 'bricomarche.com' },
    { name: 'Saint Maclou', domain: 'saint-maclou.com' },
    { name: 'Poivre Rouge', domain: 'poivrebleu.fr' },
    { name: 'Floa Bank', domain: 'floabank.fr' },
    { name: 'Auchan Retail', domain: 'auchan.fr' },
    { name: 'Cora', domain: 'cora.fr' },
    { name: 'Match', domain: 'supermatch.fr' },
    { name: 'Grand Frais', domain: 'grand-frais.com' },
    { name: 'Grand Optical', domain: 'grandoptical.com' },
    { name: 'Krys', domain: 'krys.com' },
    { name: 'Afflelou', domain: 'afflelou.com' },
    { name: 'Atol', domain: 'atol.fr' },
    { name: 'Happy Cash', domain: 'happycash.fr' },
    { name: 'Cash Converters', domain: 'cashconverters.fr' },
    { name: 'Bureau Vallée', domain: 'bureauvallee.fr' },
  ],

  'Services B2B': [
    { name: 'Sodexo', domain: 'sodexo.com' },
    { name: 'Edenred', domain: 'edenred.fr' },
    { name: 'Elior', domain: 'elior.com' },
    { name: 'Atalian', domain: 'atalian.fr' },
    { name: 'Onet', domain: 'onet.fr' },
    { name: 'Dalkia', domain: 'dalkia.fr' },
    { name: 'Spie', domain: 'spie.com' },
    { name: 'Axians', domain: 'axians.fr' },
    { name: 'Securitas', domain: 'securitas.fr' },
    { name: 'Prosegur', domain: 'prosegur.fr' },
    { name: 'Ortec', domain: 'ortec.fr' },
    { name: 'ISS France', domain: 'issworld.com' },
    { name: 'Compass Group', domain: 'compass-group.fr' },
    { name: 'Derichebourg', domain: 'derichebourg.com' },
    { name: 'Bouygues Energies', domain: 'bouygues-es.com' },
    { name: 'Samsic', domain: 'samsic.fr' },
    { name: 'Elis', domain: 'elis.com' },
    { name: 'Idex', domain: 'idex.fr' },
    { name: 'Vinci Facilities', domain: 'vinci.com' },
    { name: 'Engie Solutions', domain: 'engie.fr' },
    { name: 'Atalian Servest', domain: 'atalian.fr' },
    { name: 'Elior Services', domain: 'elior.com' },
    { name: 'Groupe Cofely', domain: 'cofely-gdfsuez.fr' },
    { name: 'Albatros Facility', domain: 'albatros-facility.fr' },
    { name: 'GSF', domain: 'gsf.fr' },
    { name: 'Vert Marine', domain: 'vert-marine.com' },
    { name: 'Récipro-Cité', domain: 'recipro-cite.com' },
    { name: 'Fiducial', domain: 'fiducial.fr' },
    { name: 'Exia', domain: 'exia.fr' },
    { name: 'Groupe Econocom', domain: 'econocom.com' },
    { name: 'Ricoh France', domain: 'ricoh.fr' },
    { name: 'Xerox France', domain: 'xerox.fr' },
    { name: 'Pitney Bowes France', domain: 'pitneybowes.fr' },
    { name: 'Lyreco France', domain: 'lyreco.fr' },
    { name: 'Raja Group', domain: 'raja.fr' },
    { name: 'Bruneau', domain: 'bruneau.fr' },
    { name: 'Staples France', domain: 'staples.fr' },
    { name: 'Bong France', domain: 'bong.fr' },
    { name: 'Antalis', domain: 'antalis.fr' },
    { name: 'Crown Holdings France', domain: 'crowncork.fr' },
  ],

  'Tech / Numérique': [
    { name: 'Capgemini', domain: 'capgemini.com' },
    { name: 'Sopra Steria', domain: 'soprasteria.com' },
    { name: 'Atos', domain: 'atos.net' },
    { name: 'CGI', domain: 'cgi.com' },
    { name: 'Wavestone', domain: 'wavestone.com' },
    { name: 'Accenture France', domain: 'accenture.com' },
    { name: 'IBM France', domain: 'ibm.com' },
    { name: 'Dassault Systèmes', domain: 'dassault-systemes.com' },
    { name: 'OVHcloud', domain: 'ovhcloud.com' },
    { name: 'Devoteam', domain: 'devoteam.com' },
    { name: 'Alten', domain: 'alten.fr' },
    { name: 'Cegid', domain: 'cegid.com' },
    { name: 'Inetum', domain: 'inetum.com' },
    { name: 'Econocom', domain: 'econocom.com' },
    { name: 'Aubay', domain: 'aubay.com' },
    { name: 'Axway', domain: 'axway.com' },
    { name: 'Talend', domain: 'talend.com' },
    { name: 'Criteo', domain: 'criteo.com' },
    { name: 'Blablacar', domain: 'blablacar.fr' },
    { name: 'Doctolib', domain: 'doctolib.fr' },
    { name: 'Qonto', domain: 'qonto.com' },
    { name: 'Payfit', domain: 'payfit.com' },
    { name: 'Contentsquare', domain: 'contentsquare.com' },
    { name: 'Mirakl', domain: 'mirakl.com' },
    { name: 'Leboncoin', domain: 'leboncoin.fr' },
    { name: 'ManoMano', domain: 'manomano.fr' },
    { name: 'Alan', domain: 'alan.com' },
    { name: 'Sewan', domain: 'sewan.fr' },
    { name: 'Infovista', domain: 'infovista.com' },
    { name: 'Micropole', domain: 'micropole.com' },
    { name: 'Hardis Group', domain: 'hardis-group.com' },
    { name: 'Absyss', domain: 'absyss.fr' },
    { name: 'Norsys', domain: 'norsys.fr' },
    { name: 'Extia', domain: 'extia.fr' },
    { name: 'Sogetrel', domain: 'sogetrel.fr' },
    { name: 'Umanlink', domain: 'umanlink.com' },
    { name: 'Betclic', domain: 'betclic.fr' },
    { name: 'Withings', domain: 'withings.com' },
    { name: 'Alma', domain: 'getalma.eu' },
    { name: 'Spendesk', domain: 'spendesk.com' },
    { name: 'Luko', domain: 'luko.eu' },
    { name: 'Lydia', domain: 'lydia-app.com' },
    { name: 'Pennylane', domain: 'pennylane.com' },
    { name: 'Meero', domain: 'meero.com' },
    { name: 'Younited Credit', domain: 'younited-credit.com' },
  ],

  'Santé / Pharma': [
    { name: 'Sanofi', domain: 'sanofi.com' },
    { name: 'Pierre Fabre', domain: 'pierre-fabre.com' },
    { name: 'Ipsen', domain: 'ipsen.com' },
    { name: 'Servier', domain: 'servier.fr' },
    { name: 'Biomérieux', domain: 'biomerieux.fr' },
    { name: 'Boiron', domain: 'boiron.fr' },
    { name: 'Urgo', domain: 'urgo.fr' },
    { name: 'Roche France', domain: 'roche.fr' },
    { name: 'Novartis France', domain: 'novartis.fr' },
    { name: 'Pfizer France', domain: 'pfizer.fr' },
    { name: 'AstraZeneca France', domain: 'astrazeneca.fr' },
    { name: 'Abbvie France', domain: 'abbvie.fr' },
    { name: 'Takeda France', domain: 'takeda.com' },
    { name: 'Arkopharma', domain: 'arkopharma.fr' },
    { name: 'Guerbet', domain: 'guerbet.com' },
    { name: 'Fresenius', domain: 'fresenius.fr' },
    { name: 'Medtronic France', domain: 'medtronic.fr' },
    { name: 'Essilor', domain: 'essilor.fr' },
    { name: 'Eurofins', domain: 'eurofins.fr' },
    { name: 'Cerba Healthcare', domain: 'cerba-healthcare.com' },
    { name: 'Ramsay Santé', domain: 'ramsay-sante.fr' },
    { name: 'Orpea', domain: 'orpea.fr' },
    { name: 'Korian', domain: 'korian.com' },
    { name: 'DomusVi', domain: 'domusvi.com' },
    { name: 'Almaviva Santé', domain: 'almaviva-sante.com' },
    { name: 'Elsan', domain: 'elsan.care' },
    { name: 'Vivalto Santé', domain: 'vivalto-sante.com' },
    { name: 'Clariane', domain: 'clariane.com' },
    { name: 'Groupe Hospitalier Diaconesses', domain: 'diaconesses.fr' },
    { name: 'Générale de Santé', domain: 'generale-de-sante.fr' },
    { name: 'Labco', domain: 'labco.fr' },
    { name: 'Unilabs France', domain: 'unilabs.fr' },
    { name: 'Synlab France', domain: 'synlab.fr' },
    { name: 'Bio Mérieux', domain: 'biomerieux.com' },
    { name: 'Biomnis', domain: 'biomnis.com' },
  ],

  'Finance / Banque': [
    { name: 'BNP Paribas', domain: 'bnpparibas.fr' },
    { name: 'Société Générale', domain: 'societegenerale.fr' },
    { name: 'Crédit Agricole', domain: 'credit-agricole.fr' },
    { name: 'Crédit Mutuel', domain: 'creditmutuel.fr' },
    { name: 'La Banque Postale', domain: 'labanquepostale.fr' },
    { name: "Caisse d'Épargne", domain: 'caisse-epargne.fr' },
    { name: 'Banque Populaire', domain: 'banquepopulaire.fr' },
    { name: 'AXA France', domain: 'axa.fr' },
    { name: 'Allianz France', domain: 'allianz.fr' },
    { name: 'Groupama', domain: 'groupama.fr' },
    { name: 'Natixis', domain: 'natixis.com' },
    { name: 'Amundi', domain: 'amundi.fr' },
    { name: 'Malakoff Humanis', domain: 'malakoffhumanis.fr' },
    { name: 'Generali France', domain: 'generali.fr' },
    { name: 'Maif', domain: 'maif.fr' },
    { name: 'Macif', domain: 'macif.fr' },
    { name: 'LCL', domain: 'lcl.fr' },
    { name: 'CIC', domain: 'cic.fr' },
    { name: 'Boursorama', domain: 'boursorama.com' },
    { name: 'April', domain: 'april.fr' },
    { name: 'Covéa', domain: 'covea.fr' },
    { name: 'SwissLife France', domain: 'swisslife.fr' },
    { name: 'CNP Assurances', domain: 'cnp.fr' },
    { name: 'Arkéa', domain: 'arkea.com' },
    { name: 'Crédit du Nord', domain: 'credit-du-nord.fr' },
    { name: 'ING Direct France', domain: 'ing.fr' },
    { name: 'Axa Investment Managers', domain: 'axa-im.fr' },
    { name: 'Lazard Frères', domain: 'lazard.fr' },
    { name: 'Rothschild & Co', domain: 'rothschildandco.com' },
    { name: 'Oddo BHF', domain: 'oddo-bhf.com' },
    { name: 'Tikehau Capital', domain: 'tikehaucapital.com' },
    { name: 'Ardian', domain: 'ardian.com' },
    { name: 'Eurazeo', domain: 'eurazeo.com' },
    { name: 'Idinvest', domain: 'idinvest.com' },
    { name: 'Bpifrance', domain: 'bpifrance.fr' },
    { name: 'Caisse des Dépôts', domain: 'caissedesdepots.fr' },
    { name: 'Crédit Logement', domain: 'creditlogement.fr' },
    { name: 'Cofidis', domain: 'cofidis.fr' },
    { name: 'Cetelem', domain: 'cetelem.fr' },
    { name: 'Sofinco', domain: 'sofinco.fr' },
  ],

  'Immobilier': [
    { name: 'Nexity', domain: 'nexity.fr' },
    { name: 'Orpi', domain: 'orpi.com' },
    { name: 'Century 21', domain: 'century21.fr' },
    { name: 'Era Immobilier', domain: 'era-immobilier.fr' },
    { name: 'Guy Hoquet', domain: 'guy-hoquet.com' },
    { name: 'Laforêt', domain: 'laforet.com' },
    { name: 'Foncia', domain: 'foncia.com' },
    { name: 'Citya', domain: 'citya.com' },
    { name: 'Icade', domain: 'icade.fr' },
    { name: 'Altarea', domain: 'altarea.com' },
    { name: 'Gecina', domain: 'gecina.fr' },
    { name: 'Covivio', domain: 'covivio.eu' },
    { name: 'Primonial', domain: 'primonial.fr' },
    { name: 'Vinci Immobilier', domain: 'vinci-immobilier.com' },
    { name: 'Eiffage Immobilier', domain: 'eiffage-immobilier.com' },
    { name: 'Bassac', domain: 'bassac.fr' },
    { name: 'Sergic', domain: 'sergic.fr' },
    { name: 'CDC Habitat', domain: 'cdchabitat.fr' },
    { name: 'Paris Habitat', domain: 'parishabitat.fr' },
    { name: 'Immobilière 3F', domain: 'immobiliere3f.fr' },
    { name: 'Logirep', domain: 'logirep.fr' },
    { name: 'Seqens', domain: 'seqens.com' },
    { name: 'Domaxis', domain: 'domaxis.fr' },
    { name: 'Elogie-Siemp', domain: 'elogie.fr' },
    { name: 'I3F', domain: 'immobiliere3f.fr' },
    { name: 'Plurial Novilia', domain: 'plurialnovilia.fr' },
    { name: 'Vilogia', domain: 'vilogia.fr' },
    { name: 'Noalis', domain: 'noalis.fr' },
    { name: 'Sia Habitat', domain: 'sia-habitat.fr' },
    { name: 'Habitat du Nord', domain: 'habitatdunord.fr' },
    { name: 'Habitat 76', domain: 'habitat76.fr' },
    { name: 'Grand Delta Habitat', domain: 'grand-delta-habitat.fr' },
    { name: 'ICF Habitat', domain: 'icf-habitat.fr' },
    { name: 'Clésence', domain: 'clesence.fr' },
    { name: 'Aximo', domain: 'aximo.fr' },
  ],

  'Hôtellerie / Restauration': [
    { name: 'Accor', domain: 'accor.com' },
    { name: 'Louvre Hotels', domain: 'louvrehotels.com' },
    { name: 'B&B Hotels', domain: 'hotel-bb.com' },
    { name: 'Marriott France', domain: 'marriott.fr' },
    { name: 'McDonald\'s France', domain: 'mcdonalds.fr' },
    { name: 'Burger King France', domain: 'burgerking.fr' },
    { name: 'KFC France', domain: 'kfc.fr' },
    { name: 'Flunch', domain: 'flunch.fr' },
    { name: 'Courtepaille', domain: 'courtepaille.com' },
    { name: 'Areas', domain: 'areas.com' },
    { name: 'Newrest', domain: 'newrest.eu' },
    { name: 'Buffalo Grill', domain: 'buffalo-grill.fr' },
    { name: 'La Mie Câline', domain: 'lamiecaline.com' },
    { name: 'Paul', domain: 'paul.fr' },
    { name: 'Brioche Dorée', domain: 'briochedoree.fr' },
    { name: 'Campanile', domain: 'campanile.com' },
    { name: 'Groupe Flo', domain: 'groupeflo.fr' },
    { name: 'Hippopotamus', domain: 'hippopotamus.fr' },
    { name: 'Léon de Bruxelles', domain: 'leon-de-bruxelles.fr' },
    { name: 'Ibis Hotels', domain: 'ibis.com' },
    { name: 'Novotel', domain: 'novotel.com' },
    { name: 'Mercure Hotels', domain: 'mercure.com' },
    { name: 'Relais & Châteaux', domain: 'relaischateaux.com' },
    { name: 'Eat Salad', domain: 'eatsalad.com' },
    { name: 'Five Guys France', domain: 'fiveguys.fr' },
    { name: 'Domino\'s Pizza', domain: 'dominos.fr' },
    { name: 'La Boîte à Pizza', domain: 'laboiteapizza.fr' },
    { name: 'Groupe Bertrand', domain: 'groupe-bertrand.com' },
    { name: 'Sodebo Restauration', domain: 'sodebo.fr' },
    { name: 'Saveurs et Vie', domain: 'saveurserie.fr' },
    { name: 'O2 Cuisines', domain: 'o2cuisines.fr' },
    { name: 'Lunch Garden', domain: 'lunchgarden.fr' },
    { name: 'Class\'croute', domain: 'classcroute.fr' },
    { name: 'Restalliance', domain: 'restalliance.fr' },
    { name: 'Dupont Restauration', domain: 'dupont-restauration.fr' },
  ],

  'Éducation / Formation': [
    { name: 'Groupe IGS', domain: 'groupe-igs.fr' },
    { name: 'Groupe INSEEC', domain: 'inseec.com' },
    { name: 'KEDGE Business School', domain: 'kedge.edu' },
    { name: 'SKEMA', domain: 'skema.edu' },
    { name: 'EDHEC', domain: 'edhec.edu' },
    { name: 'EM Lyon', domain: 'emlyon.com' },
    { name: 'Grenoble EM', domain: 'grenoble-em.com' },
    { name: 'Cesi', domain: 'cesi.fr' },
    { name: 'Afpa', domain: 'afpa.fr' },
    { name: 'OpenClassrooms', domain: 'openclassrooms.com' },
    { name: 'Studi', domain: 'studi.fr' },
    { name: 'Cegos', domain: 'cegos.fr' },
    { name: 'Demos', domain: 'demos.fr' },
    { name: 'Pigier', domain: 'pigier.com' },
    { name: 'Abilways', domain: 'abilways.fr' },
    { name: 'Ionis Education', domain: 'ionis-education-group.com' },
    { name: 'Montpellier Business School', domain: 'montpellier-bs.com' },
    { name: 'ICN Business School', domain: 'icn-artem.com' },
    { name: 'Excelia Group', domain: 'excelia-group.com' },
    { name: 'Formaposte', domain: 'formaposte.fr' },
    { name: 'M2i Formation', domain: 'm2iformation.fr' },
    { name: 'Orsys', domain: 'orsys.fr' },
    { name: 'Comundi', domain: 'comundi.fr' },
    { name: 'EFE', domain: 'efe.fr' },
    { name: 'Gereso', domain: 'gereso.fr' },
    { name: 'ISM', domain: 'ism.fr' },
    { name: 'Lamy Formation', domain: 'lamy-formation.fr' },
    { name: 'Reed Business School', domain: 'reedbs.com' },
    { name: 'Business France', domain: 'businessfrance.fr' },
    { name: 'CCI Paris Ile-de-France', domain: 'cci-paris-idf.fr' },
    { name: 'CCI Lyon Métropole', domain: 'lyon-metropole.cci.fr' },
    { name: 'Pôle Emploi Formation', domain: 'pole-emploi.fr' },
    { name: 'Uniformation', domain: 'uniformation.fr' },
    { name: 'Constructys', domain: 'constructys.fr' },
    { name: 'Atlas OPCO', domain: 'opco-atlas.fr' },
  ],

  'Énergie / Environnement': [
    { name: 'EDF', domain: 'edf.fr' },
    { name: 'Engie', domain: 'engie.fr' },
    { name: 'TotalEnergies', domain: 'totalenergies.fr' },
    { name: 'Veolia', domain: 'veolia.fr' },
    { name: 'Suez', domain: 'suez.com' },
    { name: 'Enedis', domain: 'enedis.fr' },
    { name: 'GRTgaz', domain: 'grtgaz.com' },
    { name: 'GRDF', domain: 'grdf.fr' },
    { name: 'RTE', domain: 'rte-france.com' },
    { name: 'Voltalia', domain: 'voltalia.com' },
    { name: 'Neoen', domain: 'neoen.com' },
    { name: 'Akuo Energy', domain: 'akuo.energy' },
    { name: 'Boralex', domain: 'boralex.com' },
    { name: 'Engie Green', domain: 'engie-green.fr' },
    { name: 'EDF Renouvelables', domain: 'edf-renouvelables.com' },
    { name: 'Paprec', domain: 'paprec.com' },
    { name: 'Séché Environnement', domain: 'groupe-seche.com' },
    { name: 'Saur', domain: 'saur.fr' },
    { name: 'Dalkia', domain: 'dalkia.fr' },
    { name: 'Storengy', domain: 'storengy.com' },
    { name: 'Valorem', domain: 'valorem.fr' },
    { name: 'Eolfi', domain: 'eolfi.com' },
    { name: 'Lyonnaise des Eaux', domain: 'lyonnaise-des-eaux.fr' },
    { name: 'Ortec Environnement', domain: 'ortec.fr' },
    { name: 'Ecolog France', domain: 'ecolog.fr' },
    { name: 'Groupe Pizzorno', domain: 'pizzorno.fr' },
    { name: 'Trédi', domain: 'tredi.fr' },
    { name: 'Chimirec', domain: 'chimirec.fr' },
    { name: 'Suez RR', domain: 'suez-recyclage-valorisation.fr' },
    { name: 'Veolia Propreté', domain: 'veolia.fr' },
    { name: 'Eco-Emballages', domain: 'citeo.com' },
    { name: 'Adelphe', domain: 'adelphe.fr' },
    { name: 'Terreal', domain: 'terreal.com' },
    { name: 'Lhoist France', domain: 'lhoist.fr' },
    { name: 'GSM Granulats', domain: 'gsm-granulats.fr' },
  ],

  'Ressources Humaines': [
    { name: 'Manpower', domain: 'manpower.fr' },
    { name: 'Adecco', domain: 'adecco.fr' },
    { name: 'Randstad', domain: 'randstad.fr' },
    { name: 'Michael Page', domain: 'michaelpage.fr' },
    { name: 'Robert Half', domain: 'roberthalf.fr' },
    { name: 'Hays France', domain: 'hays.fr' },
    { name: 'Page Personnel', domain: 'pagepersonnel.fr' },
    { name: 'Fed Group', domain: 'fedgroup.fr' },
    { name: 'Expectra', domain: 'expectra.fr' },
    { name: 'Synergie', domain: 'synergie.fr' },
    { name: 'Proman', domain: 'proman.fr' },
    { name: 'Groupe Crit', domain: 'groupecrit.fr' },
    { name: 'Adequat', domain: 'adequat-emploi.com' },
    { name: 'Actual Group', domain: 'actual.fr' },
    { name: 'Partnaire', domain: 'partnaire.fr' },
    { name: 'Gi Group', domain: 'gigroup.fr' },
    { name: 'Kelly Services', domain: 'kellyservices.fr' },
    { name: 'Start People', domain: 'startpeople.fr' },
    { name: 'Lucca', domain: 'lucca.fr' },
    { name: 'Altedia', domain: 'altedia.fr' },
    { name: 'BPI Group', domain: 'bpigroup.fr' },
    { name: 'Mercer France', domain: 'mercer.fr' },
    { name: 'Spencer Stuart', domain: 'spencerstuart.com' },
    { name: 'Korn Ferry', domain: 'kornferry.com' },
    { name: 'Boyden France', domain: 'boyden.com' },
    { name: 'Eureka Recrutement', domain: 'eureka-recrutement.fr' },
    { name: 'Clémentine', domain: 'clementine.jobs' },
    { name: 'Talentpeople', domain: 'talentpeople.fr' },
    { name: 'Apec', domain: 'apec.fr' },
    { name: 'Lincoln Associés', domain: 'lincoln.fr' },
    { name: 'Fyte', domain: 'fyte.com' },
    { name: 'Instaff', domain: 'instaff.fr' },
    { name: 'Vivatech RH', domain: 'vivatech.fr' },
    { name: 'Grafton Recruitment', domain: 'grafton.fr' },
    { name: 'Talents & Associés', domain: 'talents-associes.com' },
  ],

  'Conseil / Audit': [
    { name: 'Deloitte France', domain: 'deloitte.fr' },
    { name: 'PwC France', domain: 'pwc.fr' },
    { name: 'KPMG France', domain: 'kpmg.fr' },
    { name: 'EY France', domain: 'ey.com' },
    { name: 'McKinsey France', domain: 'mckinsey.com' },
    { name: 'BCG France', domain: 'bcg.com' },
    { name: 'Bain France', domain: 'bain.com' },
    { name: 'Roland Berger', domain: 'rolandberger.com' },
    { name: 'Oliver Wyman', domain: 'oliverwyman.com' },
    { name: 'AT Kearney', domain: 'kearney.com' },
    { name: 'Mazars', domain: 'mazars.fr' },
    { name: 'Grant Thornton', domain: 'grantthornton.fr' },
    { name: 'BDO France', domain: 'bdo.fr' },
    { name: 'Accuracy', domain: 'accuracy.com' },
    { name: 'Eight Advisory', domain: 'eight-advisory.com' },
    { name: 'Sia Partners', domain: 'sia-partners.com' },
    { name: 'Colombus Consulting', domain: 'colombus-consulting.com' },
    { name: 'Onepoint', domain: 'groupeonepoint.com' },
    { name: 'Wavestone', domain: 'wavestone.com' },
    { name: 'Kurt Salmon', domain: 'kurtsalmon.com' },
    { name: 'Ailancy', domain: 'ailancy.com' },
    { name: 'Citwell', domain: 'citwell.com' },
    { name: 'Argon & Co', domain: 'argonco.com' },
    { name: 'Square Management', domain: 'squaremanagement.fr' },
    { name: 'Kea & Partners', domain: 'kea-partners.com' },
    { name: 'Bearing Point', domain: 'bearingpoint.com' },
    { name: 'Capco France', domain: 'capco.com' },
    { name: 'Vertuo Conseil', domain: 'vertuo-conseil.fr' },
    { name: 'Advolis', domain: 'advolis.com' },
    { name: 'Tallis Consulting', domain: 'tallis-consulting.com' },
    { name: 'TNP Consultants', domain: 'tnp-consultants.com' },
    { name: 'Julhiet Sterwen', domain: 'julhiet-sterwen.com' },
    { name: 'Mc2i', domain: 'mc2i.fr' },
    { name: 'Weave', domain: 'weave.eu' },
    { name: 'Elixir Advisory', domain: 'elixir-advisory.com' },
  ],

  'Médias / Communication': [
    { name: 'TF1 Group', domain: 'tf1.fr' },
    { name: 'France Télévisions', domain: 'francetelevisions.fr' },
    { name: 'M6 Group', domain: 'm6.fr' },
    { name: 'Canal+', domain: 'canalplus.com' },
    { name: 'Radio France', domain: 'radiofrance.fr' },
    { name: 'Le Monde', domain: 'lemonde.fr' },
    { name: 'Le Figaro', domain: 'lefigaro.fr' },
    { name: 'Publicis', domain: 'publicisgroupe.com' },
    { name: 'Havas', domain: 'havas.com' },
    { name: 'BETC', domain: 'betc.com' },
    { name: 'Ogilvy France', domain: 'ogilvy.com' },
    { name: 'McCann France', domain: 'mccann.fr' },
    { name: 'TBWA France', domain: 'tbwa.fr' },
    { name: 'Kantar France', domain: 'kantar.com' },
    { name: 'Ipsos France', domain: 'ipsos.fr' },
    { name: 'Prisma Media', domain: 'prismamedia.com' },
    { name: 'Libération', domain: 'liberation.fr' },
    { name: 'Les Échos', domain: 'lesechos.fr' },
    { name: 'La Tribune', domain: 'latribune.fr' },
    { name: 'Ouest France', domain: 'ouest-france.fr' },
    { name: 'La Dépêche', domain: 'ladepeche.fr' },
    { name: 'Le Progrès', domain: 'leprogres.fr' },
    { name: 'Sud Ouest', domain: 'sudouest.fr' },
    { name: 'Reworld Media', domain: 'reworldmedia.com' },
    { name: 'Webedia', domain: 'webedia.fr' },
    { name: 'Amaury Médias', domain: 'amaurymedia.fr' },
    { name: 'L\'Équipe', domain: 'lequipe.fr' },
    { name: 'Challenges', domain: 'challenges.fr' },
    { name: 'Capital', domain: 'capital.fr' },
    { name: 'BBDO France', domain: 'bbdo.fr' },
    { name: 'DDB Paris', domain: 'ddb.fr' },
    { name: 'Leo Burnett France', domain: 'leoburnett.fr' },
    { name: 'Grey Paris', domain: 'grey.com' },
    { name: 'Wunderman Thompson', domain: 'wundermanthompson.com' },
    { name: 'Dentsu France', domain: 'dentsu.com' },
  ],

};

function getCompaniesByRegion(secteur, ville, limit) {
  const toutes = DOMAINES_PAR_SECTEUR[secteur] || [];

  const regionMap = {
    'lyon': ['savoie', 'rhone', 'auvergne', 'lyon', 'grenoble'],
    'paris': ['paris', 'idf', 'ile-de-france', 'versailles'],
    'marseille': ['marseille', 'paca', 'provence', 'alpes'],
    'bordeaux': ['bordeaux', 'gironde', 'aquitaine'],
    'toulouse': ['toulouse', 'occitanie', 'midi'],
    'nantes': ['nantes', 'loire', 'bretagne', 'pays-de-la-loire'],
    'lille': ['lille', 'nordpasdecalais', 'hauts-de-france'],
    'strasbourg': ['strasbourg', 'alsace', 'grandest'],
    'nice': ['nice', 'coted azur', 'alpes-maritimes'],
    'montpellier': ['montpellier', 'herault', 'languedoc'],
    'rennes': ['rennes', 'bretagne', 'ille-et-vilaine'],
    'grenoble': ['grenoble', 'isere', 'alpes'],
  };

  const villeLower = (ville || '').toLowerCase();

  let motsRegion = [];
  for (const [key, mots] of Object.entries(regionMap)) {
    if (villeLower.includes(key)) {
      motsRegion = mots;
      break;
    }
  }

  if (motsRegion.length > 0) {
    const locales = toutes.filter(c =>
      motsRegion.some(m => c.domain.includes(m) || c.name.toLowerCase().includes(m))
    );
    const autres = toutes.filter(c =>
      !motsRegion.some(m => c.domain.includes(m) || c.name.toLowerCase().includes(m))
    );
    return [...locales, ...autres].slice(0, limit);
  }

  return toutes.slice(0, limit);
}

module.exports = { DOMAINES_PAR_SECTEUR, getCompaniesByRegion };
